fix(install): manythings

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,12 +1,5 @@
 #!/usr/bin/env bash
 
-# check is curl installed or not
-if ! command -v curl &> /dev/null
-then
-    echo "commit uses curl for downloading files, please install curl and try again"
-    exit
-fi
-
 # Reset
 Color_Off=''
 
@@ -60,21 +53,28 @@ success() {
     echo -e "${Bold_Breen}$@ ${Color_Off}"
 }
 
+# check is curl installed or not
+if ! command -v curl &> /dev/null
+then
+    error "commit uses curl for downloading files, please install curl and try again"
+fi
+
 bold_success
 bold_success █▀▀ █▀█ █▀▄▀█ █▀▄▀█ █ ▀█▀
 bold_success █▄▄ █▄█ █░▀░█ █░▀░█ █ ░█░
 bold_success
 
-echo
 echo -e "${Yellow}Commit${Color_Off} helps in better git experience and maintain proper commit messages."
 info "Commit uses gum for styling prompts."
 echo
+info "Installing..."
 
 GUM_INSTALL_SETTING=$(echo 'deb [trusted=yes] https://repo.charm.sh/apt/ /' | sudo tee /etc/apt/sources.list.d/charm.list)
-GUM_INSTALL_LOG=$(sudo apt-get install gum)
+UPDATE_LOG=$(sudo apt-get update)
+GUM_INSTALL_LOG=$(sudo apt-get -y install gum)
 GUM_VERSION=$(gum -v)
 
-gum spin --spinner dot --title "Downloading gum..." --spinner.foreground="80" -- sleep 5 && echo -e "$GUM_VERSION downloaded. ${Cyan}https://github.com/charmbracelet/gum${Color_Off}" || exit 1
+gum spin --spinner dot --title "Downloading gum..." --spinner.foreground="80" -- sleep 5 && echo -e "$GUM_VERSION downloaded. ${Cyan}https://github.com/charmbracelet/gum${Color_Off}" 
 
 commit_uri=https://raw.githubusercontent.com/KunalSin9h/commit/master/commit
 
@@ -91,14 +91,14 @@ if [[ ! -d $bin_dir ]]; then
 fi
 
 curl -fsSL --fail --location --output "$sh" "$commit_uri" ||
-    echo -e  "${Red}Failed${Color_Off} to download commit from ${Cyan}\"$commit_uri\"${Color_Off}" && exit 1
+  error "Failed to download commit from \"$commit_uri\""
 
 gum spin --spinner dot --title "Downloading commit..." --spinner.foreground="80" -- sleep 5  && echo -e "commit version v0.0.1 (.) downloaded. ${Cyan}https://github.com/KunalSin9h/commit${Color_Off}"
 
 gum spin --spinner dot --title "Setting Up..." --spinner.foreground="80" -- sleep 3
 
 chmod +x "$sh" ||
-    error 'Failed to set permissions on commit executable' && exit 1
+    error 'Failed to set permissions on commit executable'
 
 tildify() {
     if [[ $1 = $HOME/* ]]; then
@@ -185,7 +185,7 @@ zsh)
     fi
     ;;
 *)
-    echo 'Manually add the directory to ~/.bashrc (or similar):'
+    echo -e "Manually add the directory to ${Yellow}~/.bashrc${Color_Off} (or similar):"
     info_bold "  export $install_env=$quoted_install_dir"
     info_bold "  export PATH=\"$bin_env:\$PATH\""
     ;;
